import type { EventDoc } from '@/types/domain';

/**
 * Showcase fixture events.
 *
 * Real, complete EventDoc records used to render live `<Invitation />` components on the
 * marketing and landing pages. Covers all high-frequency consumer occasions: Birthdays,
 * Graduations, Weddings, Baby Showers, Parties, Dinners/Galas, and Memorials.
 */
export interface ShowcaseItem {
  id: string;
  label: string;
  tagline: string;
  event: EventDoc;
}

const NOW = 1788000000000; // Static anchor timestamp for consistent SSR rendering

export const showcaseItems: readonly ShowcaseItem[] = [
  {
    id: 'birthday',
    label: 'Birthday Party',
    tagline: 'Milestone birthdays & celebrations with live guest photo sharing',
    event: {
      id: 'showcase-birthday',
      title: "Maya's 40th Birthday Celebration",
      description: 'Join us for drinks, dinner, and late-night music under the city skyline.',
      occasion: 'birthday',
      hostUid: 'usr_showcase_1',
      hostName: 'Maya Lin',
      hostedBy: 'Maya & Sam',
      templateId: 'midnight',
      status: 'live',
      startsAt: NOW + 86400000 * 14 + 3600000 * 19,
      endsAt: NOW + 86400000 * 14 + 3600000 * 24,
      timeZone: 'America/New_York',
      location: {
        name: 'The Skylight Rooftop Loft',
        address: '420 West 14th St, New York, NY',
        url: 'https://maps.google.com',
        placeId: 'ChIJOwg_06VPwokRYv534QaPC8g',
      },
      dressCode: 'Festive cocktail attire',
      rsvp: {
        enabled: true,
        deadline: NOW + 86400000 * 7,
        allowPlusOnes: true,
        maxPartySize: 2,
        askNote: true,
        question: 'Any favorite songs or drink preferences?',
        autoRemind: true,
      },
      rsvpTally: {
        yes: 42,
        no: 6,
        maybe: 4,
        pending: 12,
        attending: 48,
      },
      settings: {
        whoCanPost: 'anyone',
        allowedKinds: ['text', 'image', 'video'],
      },
      plan: 'pro',
      createdAt: NOW - 86400000 * 3,
      expiresAt: NOW + 86400000 * 21,
      endedAt: null,
      remindersSent: [],
      memberCount: 52,
      postCount: 18,
      storageBytes: 10485760,
    },
  },
  {
    id: 'graduation',
    label: 'Graduation',
    tagline: 'High school & university commencement parties, honors & open houses',
    event: {
      id: 'showcase-graduation',
      title: 'Class of 2026 Commencement & Celebration',
      description:
        'Celebrate Sam’s graduation from Columbia University! Join us for an afternoon garden reception and toasts.',
      occasion: 'graduation',
      hostUid: 'usr_showcase_grad',
      hostName: 'The Miller Family',
      hostedBy: 'David & Karen Miller',
      templateId: 'lagoon',
      status: 'live',
      startsAt: NOW + 86400000 * 21 + 3600000 * 14,
      endsAt: NOW + 86400000 * 21 + 3600000 * 19,
      timeZone: 'America/New_York',
      location: {
        name: 'The Riverfront Pavilion & Gardens',
        address: '150 Riverside Drive, New York, NY',
        url: 'https://maps.google.com',
      },
      dressCode: 'Smart casual / garden party attire',
      rsvp: {
        enabled: true,
        deadline: NOW + 86400000 * 14,
        allowPlusOnes: true,
        maxPartySize: 4,
        askNote: true,
        question: 'Will you be attending the campus ceremony beforehand?',
        autoRemind: true,
      },
      rsvpTally: {
        yes: 68,
        no: 8,
        maybe: 5,
        pending: 15,
        attending: 76,
      },
      settings: {
        whoCanPost: 'anyone',
        allowedKinds: ['text', 'image', 'video'],
      },
      plan: 'pro',
      createdAt: NOW - 86400000 * 5,
      expiresAt: NOW + 86400000 * 30,
      endedAt: null,
      remindersSent: [],
      memberCount: 72,
      postCount: 28,
      storageBytes: 20971520,
    },
  },
  {
    id: 'wedding',
    label: 'Wedding',
    tagline: 'Elegant ceremonies, receptions & rehearsal dinners',
    event: {
      id: 'showcase-wedding',
      title: 'Sophie & Liam',
      description: 'We request the pleasure of your company as we celebrate our wedding weekend.',
      occasion: 'wedding',
      hostUid: 'usr_showcase_2',
      hostName: 'Sophie Vance',
      hostedBy: 'Sophie Vance & Liam Miller',
      templateId: 'champagne',
      status: 'live',
      startsAt: NOW + 86400000 * 45 + 3600000 * 16,
      endsAt: NOW + 86400000 * 45 + 3600000 * 23,
      timeZone: 'America/New_York',
      location: {
        name: 'The Glasshouse at Willow Creek',
        address: '88 Meadowbrook Lane, Hudson Valley, NY',
        url: 'https://maps.google.com',
        placeId: 'ChIJN1t_tDeuEmsRUsoyG83frY4',
      },
      dressCode: 'Black tie optional',
      rsvp: {
        enabled: true,
        deadline: NOW + 86400000 * 30,
        allowPlusOnes: true,
        maxPartySize: 2,
        askNote: true,
        question: 'Dietary requirements or allergies?',
        autoRemind: true,
      },
      rsvpTally: {
        yes: 118,
        no: 14,
        maybe: 8,
        pending: 22,
        attending: 142,
      },
      settings: {
        whoCanPost: 'members',
        allowedKinds: ['text', 'image', 'video'],
      },
      plan: 'pro',
      createdAt: NOW - 86400000 * 10,
      expiresAt: NOW + 86400000 * 60,
      endedAt: null,
      remindersSent: [],
      memberCount: 140,
      postCount: 64,
      storageBytes: 41943040,
    },
  },
  {
    id: 'baby',
    label: 'Baby Shower',
    tagline: 'Warm family welcomes & registries with zero ads',
    event: {
      id: 'showcase-baby',
      title: 'A Shower for Baby Charlotte',
      description:
        'Join us for afternoon tea, sweet treats, and celebrating mama-to-be Jessica.',
      occasion: 'baby',
      hostUid: 'usr_showcase_baby',
      hostName: 'Hannah & Claire',
      hostedBy: 'Hannah & Claire',
      templateId: 'blossom',
      status: 'live',
      startsAt: NOW + 86400000 * 18 + 3600000 * 13,
      endsAt: NOW + 86400000 * 18 + 3600000 * 16,
      timeZone: 'America/New_York',
      location: {
        name: 'The Conservatory Garden Room',
        address: '540 Park Avenue, New York, NY',
        url: 'https://maps.google.com',
      },
      dressCode: 'Pastel / tea party attire',
      rsvp: {
        enabled: true,
        deadline: NOW + 86400000 * 10,
        allowPlusOnes: false,
        maxPartySize: 1,
        askNote: true,
        question: 'Any dietary restrictions?',
        autoRemind: true,
      },
      rsvpTally: {
        yes: 32,
        no: 4,
        maybe: 2,
        pending: 6,
        attending: 32,
      },
      settings: {
        whoCanPost: 'anyone',
        allowedKinds: ['text', 'image'],
      },
      plan: 'free',
      createdAt: NOW - 86400000 * 4,
      expiresAt: NOW + 86400000 * 20,
      endedAt: null,
      remindersSent: [],
      memberCount: 36,
      postCount: 16,
      storageBytes: 6291456,
    },
  },
  {
    id: 'party',
    label: 'Party & Night Out',
    tagline: 'High-energy gatherings, rooftop mixers & housewarming parties',
    event: {
      id: 'showcase-party',
      title: 'Midsummer Sunset & DJ Set',
      description:
        'Live DJs, craft cocktails, and sunset views from the terrace. Come early, stay late.',
      occasion: 'party',
      hostUid: 'usr_showcase_party',
      hostName: 'Julian & Alex',
      hostedBy: 'Julian & Alex',
      templateId: 'ember',
      status: 'live',
      startsAt: NOW + 86400000 * 9 + 3600000 * 20,
      endsAt: NOW + 86400000 * 10 + 3600000 * 2,
      timeZone: 'America/New_York',
      location: {
        name: 'The Highline Rooftop Terrace',
        address: '500 West 24th St, New York, NY',
        url: 'https://maps.google.com',
      },
      dressCode: 'Summer evening / chic',
      rsvp: {
        enabled: true,
        deadline: NOW + 86400000 * 5,
        allowPlusOnes: true,
        maxPartySize: 2,
        askNote: true,
        question: 'Song requests for the DJ set?',
        autoRemind: true,
      },
      rsvpTally: {
        yes: 85,
        no: 12,
        maybe: 14,
        pending: 20,
        attending: 98,
      },
      settings: {
        whoCanPost: 'anyone',
        allowedKinds: ['text', 'image', 'video', 'audio'],
      },
      plan: 'pro',
      createdAt: NOW - 86400000 * 2,
      expiresAt: NOW + 86400000 * 14,
      endedAt: null,
      remindersSent: [],
      memberCount: 92,
      postCount: 42,
      storageBytes: 31457280,
    },
  },
  {
    id: 'retirement',
    label: 'Dinner & Gala',
    tagline: 'Distinguished milestones, retirement galas & formal banquets',
    event: {
      id: 'showcase-retirement',
      title: 'Dr. Harper’s Retirement Gala',
      description:
        'Honoring 35 years of clinical excellence, research, and mentorship in neurosurgery.',
      occasion: 'dinner',
      hostUid: 'usr_showcase_3',
      hostName: 'Dr. Elena Rostova',
      hostedBy: 'The Department of Neurological Surgery',
      templateId: 'botanical',
      status: 'live',
      startsAt: NOW + 86400000 * 20 + 3600000 * 18 + 3600000 * 0.5,
      endsAt: NOW + 86400000 * 20 + 3600000 * 22,
      timeZone: 'America/New_York',
      location: {
        name: 'The University Club Ballroom',
        address: '1 West 54th St, New York, NY',
        url: 'https://maps.google.com',
      },
      dressCode: 'Semi-formal / business attire',
      rsvp: {
        enabled: true,
        deadline: NOW + 86400000 * 10,
        allowPlusOnes: true,
        maxPartySize: 2,
        askNote: true,
        question: 'Will you be giving a brief tribute or toast?',
        autoRemind: true,
      },
      rsvpTally: {
        yes: 74,
        no: 12,
        maybe: 5,
        pending: 10,
        attending: 86,
      },
      settings: {
        whoCanPost: 'members',
        allowedKinds: ['text', 'image'],
      },
      plan: 'pro',
      createdAt: NOW - 86400000 * 5,
      expiresAt: NOW + 86400000 * 30,
      endedAt: null,
      remindersSent: [],
      memberCount: 88,
      postCount: 32,
      storageBytes: 15728640,
    },
  },
  {
    id: 'memorial',
    label: 'Memorial',
    tagline: 'Dignified, ad-free notices with gentle memory sharing',
    event: {
      id: 'showcase-memorial',
      title: 'Remembering Arthur Davies',
      description:
        'A celebration of Arthur’s life, stories, and the quiet joy he brought to all of us.',
      occasion: 'memorial',
      hostUid: 'usr_showcase_4',
      hostName: 'The Davies Family',
      hostedBy: 'The Davies Family',
      templateId: 'linen',
      status: 'live',
      startsAt: NOW + 86400000 * 7 + 3600000 * 11,
      endsAt: NOW + 86400000 * 7 + 3600000 * 14,
      timeZone: 'America/New_York',
      location: {
        name: 'St. Jude’s Memorial Chapel & Courtyard',
        address: '210 Elm Street, Greenwich, CT',
        url: 'https://maps.google.com',
      },
      dressCode: 'Respectful attire',
      rsvp: {
        enabled: true,
        deadline: null,
        allowPlusOnes: true,
        maxPartySize: 4,
        askNote: true,
        question: null,
        autoRemind: false,
      },
      rsvpTally: {
        yes: 58,
        no: 4,
        maybe: 2,
        pending: 8,
        attending: 64,
      },
      settings: {
        whoCanPost: 'anyone',
        allowedKinds: ['text', 'image'],
      },
      plan: 'free',
      createdAt: NOW - 86400000 * 2,
      expiresAt: NOW + 86400000 * 14,
      endedAt: null,
      remindersSent: [],
      memberCount: 65,
      postCount: 24,
      storageBytes: 8388608,
    },
  },
] as const;

export const defaultShowcaseEvent = showcaseItems[0]!.event;
